In [1]:
import torch

# Take input image

In [6]:
input_img = torch.randn(1,10)

In [7]:
input_img

tensor([[-0.1358, -0.8318,  2.5724, -1.0813, -0.5210,  0.8518, -0.7374,  0.6213,
         -0.4663, -0.0081]])

# Take input for weight

In [8]:
weights = torch.randn_like(input_img)

In [9]:
weights

tensor([[ 0.5158,  1.3911, -0.3548, -0.5660, -0.3440, -0.3964,  0.3392, -0.0741,
         -1.6045,  1.3485]])

# Take input for bias

In [10]:
bias = torch.randn(1,1)

In [15]:
bias


tensor([[0.4085]])

#input_img*weights

In [16]:
# sum of  input_img*weights

# Calculating Output

 input_img*weights

In [17]:
 input_img*weights

tensor([[-0.0701, -1.1571, -0.9127,  0.6120,  0.1792, -0.3377, -0.2501, -0.0460,
          0.7482, -0.0109]])

sum of  input_img*weights

In [18]:
torch.sum( input_img*weights)

tensor(-1.2452)

 input_img*weights +weights

In [19]:
output =  torch.sum(input_img*weights)+bias 

In [20]:
output

tensor([[-0.8368]])

# Use Activation Function

use sygmoid function to sclae the value of the output between 0 and 1

#Create Sygmoid function

In [21]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))

#Pass the output to the function and store it to the output variable

In [22]:
output = sigmoid(output)

In [23]:
output

tensor([[0.3022]])