In [3]:
import torch

In [4]:
x=torch.Tensor([1,2,3])

In [5]:
x

tensor([1., 2., 3.])

In [6]:
x[2]

tensor(3.)

In [7]:
x.shape


torch.Size([3])

In [8]:
x+torch.tensor([4,4,4])

tensor([5., 6., 7.])

In [9]:
x*torch.tensor([4,4,4])

tensor([ 4.,  8., 12.])

In [10]:
x+5


tensor([6., 7., 8.])

In [12]:
x=torch.Tensor([[1,2,3],[4,5,6]])

In [13]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
x+5

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [15]:
x=torch.randn((1,5))

In [16]:
x

tensor([[ 1.3592, -1.5158,  1.1663, -0.8781, -1.7142]])

In [17]:
x=torch.randn((2,3))

In [18]:
x

tensor([[-0.2794,  1.4907,  0.1861],
        [ 0.2490,  1.0236,  1.8750]])