In [2]:
import torch

In [3]:
input_img = torch.randn(1,10)

In [4]:
input_img

tensor([[-1.9820,  0.7372, -0.5066, -1.0869,  1.3026, -0.6646,  0.2715, -1.1534,
          0.9123,  0.9513]])

In [5]:
weights = torch.randn_like(input_img)

In [6]:
weights

tensor([[ 1.1387,  0.8330,  0.4120,  0.5661,  1.0890, -0.7317, -0.6370,  0.8847,
          1.8705, -0.6116]])

In [7]:
bias = torch.randn(1,1)

In [8]:
bias

tensor([[1.3780]])

# output

In [9]:
output =  torch.sum(input_img*weights)+bias 

In [10]:
output

tensor([[0.7471]])

# Matrix Multiplication
we can do the above calculation using mm

In [12]:
output =  torch.mm(input_img,weights)+bias 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x10 and 1x10)

# for matrix multiplication mat1 and mat2 shapes must be (1x10 and 10x1)
so to get rid of the error we have to reshape input_img or weights

In [13]:
output =  torch.mm(input_img,weights.view(10,1)+bias 

SyntaxError: incomplete input (1417597070.py, line 1)