In [39]:
import torch

In [40]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))

# Take input

In [41]:
input_img = torch.randn((1,3))

In [42]:
input_img

tensor([[-0.5319, -0.4094, -0.9214]])

# Define number of  input,
# neurons
# outputs

In [43]:
n_inputs = input_img.shape

In [44]:
n_inputs

torch.Size([1, 3])

# as number of column mention the input

In [45]:
n_inputs = input_img.shape[1]

In [46]:
n_inputs

3

In [47]:
n_neurons = 2

In [48]:
n_outputs = 1

# Take input of weights

In [36]:
w1 = torch.randn((n_inputs,n_neurons))

In [37]:
w1

tensor([[ 2.7316,  0.6150],
        [ 0.1208, -0.2606],
        [-0.8714,  1.0931]])

In [49]:
w2 = torch.randn((n_neurons,n_outputs))

In [52]:
w2

tensor([[-0.2620],
        [-1.8767]])

# Bias

In [50]:
B1 = torch.randn((1,n_neurons))

In [53]:
B1

tensor([[0.4568, 2.4811]])

In [54]:
B2 = torch.randn((1,n_outputs))

In [55]:
B2

tensor([[0.1950]])

# finding h1 and output

In [56]:
h1 = sigmoid(torch.mm(input_img,w1)+B1)

In [57]:
h1

tensor([[0.4397, 0.7779]])

# finding output 

In [59]:
output = sigmoid(torch.mm(h1,w2)+B2)

In [60]:
output

tensor([[0.2010]])